name: Tests

on:
  push:
    branches:
      - 2.*
      - main
  pull_request:

jobs:
  default:

    name: Unit, Integration and Pages

    runs-on: ubuntu-latest

    env:
      APP_URL: http://localhost:8000
      APP_ENV: testing
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: ieducar
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      API_ACCESS_KEY: ieducar-access-key
      API_SECRET_KEY: ieducar-secret-key
      BROADCAST_DRIVER: log
      CACHE_DRIVER: array
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: array

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ieducar
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2
      - name: Utiliza vers√£o 2.1.14 do Composer
        run: composer self-update 2.1.14
      - name: Install Dependencies
        run: composer new-install
      - name: Unit tests
        run: vendor/bin/phpunit
      - name: Integration tests
        run: vendor/bin/phpunit --testsuite=Diario
      - name: Page tests
        run: |
          php artisan legacy:create:tests
          php artisan test --parallel --testsuite Pages
